### PR TITLE
[WIP] python 3.7 + pybind11 

### LINKED ISSUE #37: [Roadmap] Python 3.7 support plans for NimbusML
> @montebhoover What is in your team's plan around support for 3.7? The BotBuilder SDK team is _considering_ moving to Python 3.7 from 3.6; we'd like to be able to run with NimbusML out of the box, should customers decide to use the two together.
> 
> __DCR: Target Python 3.7 instead of Python 3.6 for BotBuilder-Python__ [Microsoft/BotBuilder#5112]

_Originally posted by @stevengum in https://github.com/Microsoft/NimbusML/pull/28#issuecomment-434017015_

### PR DESCRIPTION
**Pull request by ganik**
Onboards to python 3.7
Uses pybind11 instead of boost
fixes #37

### CODE REVIEW

**Comment by montebhoover** [comment]
@sdpython I'd like to join the effort if it is helpful - are there any areas or specific tests that you would want me to take a look at?

**Comment by ganik** [comment]
@montebhoover @xadupre  I suggest to split this pull request into 2 parts and attack them separately. 
Moving to Python3.7 is more needed and should be done with relative ease with boost_python
Moving to pybind11 is optional and can be done with less urgency.

**Comment by xadupre** [comment]
I agree but one of the Reason it does not work right now is I don't know are the following replacements for python 3.7: https://pythonpkgdeps.blob.core.windows.net/python/python-3.7.0-mohoov-amd64.zip and https://pythonpkgdeps.blob.core.windows.net/boost/debug/windows/Boost-3.5-1.64.0.0.zip. I cannot complete the PR or create a new one without knowing that.

**Comment by montebhoover** [comment]
@xadupre, yes, those are unfortunately opaque.   https://pythonpkgdeps.blob.core.windows.net/python/python-3.7.0-mohoov-amd64.zip is simply a zipped package of the binaries that are produced from the Python MSI installer.  There is probably a better way of getting the python executable for the build script, and I would be open to changing that.

https://pythonpkgdeps.blob.core.windows.net/boost/debug/windows/Boost-3.5-1.64.0.0.zip is another zipped package of binaries, this one the result of building Boost.Python according to the [official instructions](https://www.boost.org/doc/libs/1_69_0/libs/python/doc/html/index.html).  It takes a couple hours to set up environments and build this for all three platforms, and I can do that if it helps, or I can give more specific pointers on the official build instructions.

I'm quite excited about moving from Boost to pybind11, but in the meantime I'm happy to build the Boost binaries for Py3.7 just to get that out of the way.

**Comment by ganik** [comment]
@montebhoover I would suggest Monte to do a separate PR for python3.7, since you are very familiar with whole build flow and 3.7 specific changes should be already done in this PR by Xavier.

**Comment by ganik** [comment]
Will create a separate PR for python 3.7 only, dropping pybind11 for now

**Pull request closed without merging**
