### PR TITLE
Fix broken docs

### LINKED ISSUE #368: Documentation for some components is broken
Descriptions/remarks for several classes are messed up and there is no/incomplete documentation for some params. This is due to some incorrect indentation.

`Pipeline`: https://docs.microsoft.com/en-us/python/api/nimbusml/nimbusml.pipeline?view=nimbusml-py-latest
https://github.com/microsoft/NimbusML/blob/fb292b362e2611126e92a002691feedcabf2132b/src/python/nimbusml/pipeline.py#L121-L125

`ensemble.booster.Dart`: https://docs.microsoft.com/en-us/python/api/nimbusml/nimbusml.ensemble.booster.dart?view=nimbusml-py-latest
https://github.com/microsoft/NimbusML/blob/fb292b362e2611126e92a002691feedcabf2132b/src/python/nimbusml/ensemble/booster/dart.py#L27-L29

and several other places. Do a pass over the docs site and fix the relevant whitespacing issues.

### PR DESCRIPTION
**Pull request by najeeb-kazmi**
Fix #368 

Also fixed some typos that I found along the way.

### CODE REVIEW

**Comment by ganik** [comment]
please rebase your branch

**Comment by ganik** [comment]
>     Gradient-based One-Side Sampling.

what change here?

---
Refers to: src/python/docs/docstrings/Goss.txt:3 in 1963a2b. [](commit_id = 1963a2ba9eb24c7c47f0113dfd9c58274f70190c, deletion_comment = False)

**Comment by ganik** [comment]
> import inspect

you need to rebase your changes

---
Refers to: src/python/nimbusml/pipeline.py:5 in 1963a2b. [](commit_id = 1963a2ba9eb24c7c47f0113dfd9c58274f70190c, deletion_comment = False)

**Comment by najeeb-kazmi** [comment]
>     Gradient-based One-Side Sampling.

Changed the indentation in the remarks below. Bad indentation caused parts of the remarks to be rendered in the description. See here: [https://docs.microsoft.com/en-us/python/api/nimbusml/nimbusml.ensemble.booster.goss?view=nimbusml-py-latest](https://docs.microsoft.com/en-us/python/api/nimbusml/nimbusml.ensemble.booster.goss?view=nimbusml-py-latest)

---
In reply to: [556208481](https://github.com/microsoft/NimbusML/pull/369#issuecomment-556208481) [](ancestors = 556208481)

---
Refers to: src/python/docs/docstrings/Goss.txt:3 in 1963a2b. [](commit_id = 1963a2ba9eb24c7c47f0113dfd9c58274f70190c, deletion_comment = False)

**Comment by najeeb-kazmi** [comment]
> import inspect

done

---
In reply to: [556209275](https://github.com/microsoft/NimbusML/pull/369#issuecomment-556209275) [](ancestors = 556209275)

---
Refers to: src/python/nimbusml/pipeline.py:5 in 1963a2b. [](commit_id = 1963a2ba9eb24c7c47f0113dfd9c58274f70190c, deletion_comment = False)

**Comment by najeeb-kazmi** [comment]
done

---
In reply to: [556207428](https://github.com/microsoft/NimbusML/pull/369#issuecomment-556207428) [](ancestors = 556207428)

**Pull request merged**
