### PR TITLE
Added "# -- coding: utf-8 --" to preserve the character `␂` while guaranteeing successful builds with Python 2.7

### LINKED ISSUE #327: NimbusML-ExtendedTests failing on Linux and Mac with Python 2.7 due to "Non-ASCII character" in NGramExtractor.py and Schema.py
**Describe the bug**
NimbusML-ExtendedTests failing on Linux and Mac with Python 2.7 due to "Non-ASCII character" in NGramExtractor.py.

**To Reproduce**
Link to error output on Mac: https://dev.azure.com/aifx/public/_build/results?buildId=1730&view=logs&j=d602e5ee-b117-53e9-baca-06d38555e9ae&t=7a4bfe99-128e-548b-1b46-3dfd9c68bb4f&l=5008

Link to error output on Linux: https://dev.azure.com/aifx/public/_build/results?buildId=1730&view=logs&j=3c504bce-f2a1-5e42-8836-973c0d49cff4&t=2d074167-a29f-5a24-824f-43288b97471e&l=2145

The character `␂` is troublesome in Python 2.7 builds on Mac and Linux, as it is not recognized as a valid ASCII character.

### PR DESCRIPTION
**Pull request by mstfbl**
Fixes #327 

Replaced `␂`, which is not recognized as a valid ASCII character in Python 2.7 builds on Linux and Mac with the placeholder `.`.

### CODE REVIEW

**Comment by justinormont** [comment]
These are standard ASCII chars 0x02 & 0x03. 

Another route is seeing if Python 2.7 allows the control chars in a string literal instead of a comment. 

Larger discussion is dropping 2.7 support, which is EOL in three months.

**Comment by mstfbl** [comment]
@ganik Your suggested change worked, I am also editing the PR for Issue #289 .

**Comment by mstfbl** [comment]
I have added the commit to modify Schema.py to this PR as both the character `␂` in both Schema.py and NGramExtractor_df.py cause the build to fail for the same reasons.

**Comment by pieths** [comment]
Is the format of the comment correct? It looks like in the [PEP](https://www.python.org/dev/peps/pep-0263/) they use `-*-`.

---
In reply to: [541376373](https://github.com/microsoft/NimbusML/pull/328#issuecomment-541376373) [](ancestors = 541376373)

**Comment by ganik** [comment]
@mustafa.bal@microsoft.com can you check Pieths suggestion?

---
In reply to: [541846803](https://github.com/microsoft/NimbusML/pull/328#issuecomment-541846803) [](ancestors = 541846803,541376373)

**Comment by mstfbl** [comment]
Adding encoding with the PEP-suggested `-*-` works as well.

**Comment by pieths** [comment]
In PEP 263 it states:

>the first or second line must match the following regular expression:
> `^[ \t\f]*#.*?coding[:=][ \t]*([-_.a-zA-Z0-9]+)`

So there are lots of different formats that would work. This also explains why the first one worked. Sorry if I made the issue more difficult than it needed to be.

**Pull request merged**
